Repository Mrcoolx10011/-one-to--code, pull requests merged in 2022-10, with the labels that each got.

#1 Create abs.cpp
  abs.cpp
Labels: Hacktoberfest, hacktoberfest2022

#2 Create pythonfun.py
  pythonfun.py
Labels: Hacktoberfest, hacktoberfest2022

#3 Create special.py
  special.py
Labels: Hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#4 Create funny.py
  funny.py
Labels: Hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#5 Create fibonacci.py
  fibonacci.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#11 life.cpp
  life.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#12 save.css
  save.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#13 dab.cpp
  dab.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
